### ISSUE TITLE
[Membership]: Subproject Approver - @TylerGillson

### ISSUE THREAD

**Issue by TylerGillson** [k8sgpt-ai/community#28]
### GitHub Username

@TylerGillson

### Membership Level

Subproject Approver

### Subproject

k8sgpt-operator

### Sponsors

@AlexsJones
@thschue 

### Requirements

- I have been an active contributor to the codebase for only 1 week, but fully intend to continue making contributions.
- I have merged 2 PRs to the k8sgpt-operator codebase and contributed to the k8sgpt community separately by writing a blog post about k8sgpt and the k8sgpt operator and answering questions about it in the k8sgpt Slack.
- I have been nominated by both maintainers of the k8sgpt organization.

### List of contributions to the project

k8sgpt-operator
- https://github.com/k8sgpt-ai/k8sgpt-operator/pull/8
- https://github.com/k8sgpt-ai/k8sgpt-operator/pull/19
- https://github.com/k8sgpt-ai/k8sgpt-operator/pull/18

k8sgpt
- https://github.com/k8sgpt-ai/k8sgpt/pull/318

docs
- https://github.com/k8sgpt-ai/docs/pull/29

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributor Guide

- [X] I have read and understood the Contribution Guide

### Contributor Guide and Membership Requirements

- [X] I have read and understood the Community Membership Document

**Comment by thschue** [comment]
+1

**Comment by AlexsJones** [comment]
Great to have you, thanks for the contributions so far

**Comment by thschue** [comment]
Thank you for your contributions! Added you to the operator-approvers group!
