### ISSUE TITLE
[Membership]: Subproject Maintainer - @arbreezy

### ISSUE THREAD

**Issue by arbreezy** [k8sgpt-ai/community#37]
### GitHub Username

@arbreezy

### Membership Level

Subproject Maintainer

### Subproject

k8sgpt-operator

### Sponsors

@AlexsJones
@thschue

### Requirements

- I have been contributing to k8sgpt and k8sgpt operator for the past month
- Participating in various discussions about both projects and helping resolving issues
- Experience with operator's development 

### List of contributions to the project

k8sgpt-operator's [PRs](https://github.com/k8sgpt-ai/k8sgpt-operator/pulls?q=is%3Apr+is%3Aclosed+author%3Aarbreezy)  
  
k8sgpt's [PRs](https://github.com/k8sgpt-ai/k8sgpt/pulls?q=is%3Apr+is%3Aclosed+author%3Aarbreezy)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributor Guide

- [X] I have read and understood the Contribution Guide

### Contributor Guide and Membership Requirements

- [X] I have read and understood the Community Membership Document

**Comment by thschue** [comment]
+1

**Comment by AlexsJones** [comment]
LGTM, welcome and thank you for your continued contribution
