### ISSUE TITLE
[Membership]: Member - @rakshitgondwal

### ISSUE THREAD

**Issue by rakshitgondwal** [k8sgpt-ai/community#38]
### GitHub Username

@rakshitgondwal

### Membership Level

Organization Member

### Subproject

None

### Sponsors

@AlexsJones 
@thschue 

### Requirements

- I have been actively contributing to k8sgpt and docs.
- Written one blog around k8sgpt too.
- Participating in various discussions about the projects and new features.

### List of contributions to the project

Blogs:
- [K8sGPT: The Ultimate Tool for Kubernetes Scanning](https://blog.wemakedevs.org/k8sgpt)

PRs:
- feat: add explanation for filters [#49](https://github.com/k8sgpt-ai/docs/pull/49)
- feat: document different AI backends [#40](https://github.com/k8sgpt-ai/docs/pull/40)
- docs: add documentation for NoOpAiProvider [#18](https://github.com/k8sgpt-ai/docs/pull/18)
- feat: improve HPA analyzer to check ScaleTargetRef resources [#283](https://github.com/k8sgpt-ai/k8sgpt/pull/283)
- docs: add installation guide using rpm, deb, apk [#205](https://github.com/k8sgpt-ai/k8sgpt/pull/205)
- feat: improve analyze command [#394](https://github.com/k8sgpt-ai/k8sgpt/pull/394)

Issues:
- [Feature]: Add Netlify to Docs site [#50](https://github.com/k8sgpt-ai/docs/issues/50)
- Typo in k8sgpt version [#462](https://github.com/k8sgpt-ai/k8sgpt/issues/462)
- Installation guide using rpm, deb, apk [#14](https://github.com/k8sgpt-ai/docs/issues/14)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributor Guide

- [X] I have read and understood the Contribution Guide

### Contributor Guide and Membership Requirements

- [X] I have read and understood the Community Membership Document

**Comment by AlexsJones** [comment]
+1
