### ISSUE TITLE
When we are To deploy a K8sGPT resource

### ISSUE THREAD

**Issue by gowthamc206** [k8sgpt-ai/community#44]
### Username on the K8sGPT Slack / Twitter

mahesh

### Used Components

- [X] k8sgpt
- [X] k8sgpt-operator

### Your Story

Sorry i am not using slack and twitter please contact on maheshy1993reddy@gmail.com.

when we are deploy the a K8sGPT resource . getting this 
error: error validating "STDIN": error validating data: [ValidationError(K8sGPT): missing required field "noCache" in ai.k8sgpt.core.v1alpha1.K8sGPT, ValidationError(K8sGPT): missing required field "version" in ai.k8sgpt.core.v1alpha1.K8sGPT]; if you choose to ignore these errors, turn validation off with --validate=false

### Please check the following

- [X] I am allowed to share this story
- [X] I agree that this story can be used for project promotion purposes
- [X] I already added me and my company in the [ADOPTERS](https://github.com/k8sgpt-ai/community/blob/main/ADOPTERS.md) file

**Comment by AnaisUrlichs** [comment]
Hi there, could you please create an issue in the https://github.com/k8sgpt-ai/k8sgpt-operator/issues repository if the issue persists -- closing this issue
