### ISSUE TITLE
[Membership]: Community Approver - AnaisUrlichs

### ISSUE THREAD

**Issue by thschue** [k8sgpt-ai/community#52]
### GitHub Username

@AnaisUrlichs

### Membership Level

Subproject Approver

### Subproject

community

### Sponsors

@thschue

### Requirements

- [X] Deep understanding of the technical goals and direction of the subproject
- [X] Deep understanding of the technical domain of the subproject
- [X] Sustained contributions to design and direction by doing all of:
   * Authoring and reviewing proposals
   * Initiating, contributing and resolving discussions (emails, GitHub issues, meetings)
   * Identifying subtle or complex issues in designs and implementation PRs
- [X] Directly contributed to the subproject through implementation and / or review

### List of contributions to the project

  * https://github.com/k8sgpt-ai/community/pull/51
  * Maintainance of website / docs / community content

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributor Guide

- [X] I have read and understood the Contribution Guide

### Contributor Guide and Membership Requirements

- [X] I have read and understood the Community Membership Document

**Comment by AlexsJones** [comment]
I support this

**Comment by AnaisUrlichs** [comment]
Yes, thank you

**Comment by thschue** [comment]
Added the corresponding permissions, done
