### ISSUE TITLE
[Membership]: k8sgpt, k8sgpt-operator SubProject Approver - JuHyung-Son

### ISSUE THREAD

**Issue by JuHyung-Son** [k8sgpt-ai/community#54]
### GitHub Username

@JuHyung-Son

### Membership Level

Subproject Approver

### Subproject

k8sgpt

### Sponsors

@AlexsJones @thschue 

### Requirements

Highly experienced active reviewer and contributor to a subproject

### List of contributions to the project

testing functions.
fix bugs.
suggest and implement new features

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributor Guide

- [X] I have read and understood the Contribution Guide

### Contributor Guide and Membership Requirements

- [X] I have read and understood the Community Membership Document

**Comment by AlexsJones** [comment]
I support this

**Comment by thschue** [comment]
I also support this, welcome on board

**Comment by JuHyung-Son** [comment]
thanks!
